FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.csproj .
RUN dotnet restore

COPY . .

RUN dotnet clean
RUN rm -rf /app/publish

RUN dotnet publish -c Release -o /app/publish

COPY appsettings.Production.json /app/publish/

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./
CMD ["dotnet", "BokmalensWebbshop.dll"]