services:
  app:
    build: .
    ports:
      - "5001:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - /Users/wiktoria/Downloads/BokmalensWebbshop:/app
      - dataprotection:/root/.aspnet/DataProtection-Keys
    command: ["dotnet", "watch", "run", "--urls=http://+:8080"]

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  dataprotection:
# services:
#   app:
#     build: .
#     ports:
#       - "5001:8080"
#     depends_on:
#       db:
#         condition: service_healthy
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: ${POSTGRES_DB}
#       POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     ports:
#       - "5432:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 10