FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
WORKDIR /app

RUN dotnet tool install --global dotnet-watch
ENV PATH="$PATH:/root/.dotnet/tools"

EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--urls=http://+:8080"]